apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-app-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-web-app-test
  template:
    metadata:
      labels:
        app: nodejs-web-app-test
    spec:
      containers:
        - name: nodejs-web-app-test
          image: dopeamin/tp_kubernetes:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
