apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-web-app
  template:
    metadata:
      labels:
        app: nodejs-web-app
    spec:
      containers:
        - name: nodejs-web-app
          image: yourusername/nodejs-web-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
