apiVersion: v1
kind: Service
metadata:
  name: nodejs-web-app-service-test
spec:
  selector:
    app: nodejs-web-app-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
